pip install -e .
pip install -e ./retro_planner/packages/mlp_retrosyn/
pip install -e ./retro_planner/packages/value_function/
pip install -e ./retro_planner/packages/rxn_filter/
pip install -e ./retro_planner/packages/onmt/
pip install -e ./retro_planner/packages/easifa/
pip install -e ./retro_planner/packages/graph_retrosyn/
pip install -e ./retro_planner/packages/condition_predictor/
pip install -e ./retro_planner/packages/organic_enzyme_rxn_classifier